// Para periodos lectivos
export const ERROR_SCHOOLYEAR = 'ERROR_SCHOOLYEAR';
export const CREATE_SCHOOLYEAR = 'CREATE_SCHOOLYEAR';
export const CHECK_SCHOOLYEAR = 'CHECK_SCHOOLYEAR';
export const GET_SCHOOLYEAR = 'GET_SCHOOLYEAR';
export const CURRENT_SCHOOLYEAR = 'CURRENT_SCHOOLYEAR';
export const UPDATE_SCHOOLYEAR = 'UPDATE_SCHOOLYEAR';
export const DELETE_SCHOOLYEAR = 'DELETE_SCHOOLYEAR';

// Para cursos
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_INFO = 'GET_COURSE_INFO';
export const CREATE_COURSE = 'CREATE_COURSE';
export const CHECK_COURSE = 'CHECK_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

// Para paralelos
export const GET_PARALLEL = 'GET_PARALLEL';
export const CREATE_PARALLEL = 'CREATE_PARALLEL';
export const CHECK_PARALLEL = 'CHECK_PARALLEL';
export const UPDATE_PARALLEL = 'UPDATE_PARALLEL';
export const DELETE_PARALLEL = 'DELETE_PARALLEL';

//Para profesores
export const GET_TEACHER = 'GET_TEACHER';
export const CREATE_TEACHER = 'CREATE_TEACHER';
export const CHECK_TEACHER = 'CHECK_TEACHER';
export const ERROR_TEACHER = 'ERROR_TEACHER';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';

//Para asignaturas
export const GET_CLASS = 'GET_CLASS';
export const CREATE_CLASS = 'CREATE_CLASS';
export const CHECK_CLASS = 'CHECK_CLASS';
export const ERROR_CLASS = 'ERROR_CLASS';
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';


//Para Horarios de clases
export const SET_FORM = 'SET_FORM';
export const SET_DATA = 'SET_DATA';
export const SET_MOD_DATA = 'SET_MOD_DATA';
export const REMOVE_DATA = 'REMOVE_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';
export const ERROR_SCHEDULE = 'ERROR_SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const CREATE_AUTO = 'CREATE_AUTO';
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_SCHEDULE_BY_PARALLEL = 'GET_SCHEDULE_BY_PARALLEL';
export const CHECK_SCHEDULE = 'CHECK_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';

//Para reportes
export const GET_GROUP_REPORT = 'GET_GROUP_REPORT';
export const GET_INDIVIDUAL_REPORT = 'GET_INDIVIDUAL_REPORT';

//Para autenticacion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const AUTENTICAR_USUARIO_EXITO = 'AUTENTICAR_USUARIO_EXITO';
export const AUTENTICAR_USUARIO_ERROR = 'AUTENTICAR_USUARIO_ERROR';

//Para cuentas de usuario
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CHECK_ACCOUNT = 'CHECK_ACCOUNT';
export const ERROR_ACCOUNT = 'ERROR_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';